services:
  cmprefimpl:
    build:
      dockerfile: geos.Dockerfile
      args:
        ALPINE_VERSION: 3.19
        GEOS_VERSION: 3.12.1-r0
    working_dir: /mnt/sf
    entrypoint: go run ./internal/cmprefimpl/cmpgeos
    volumes:
      - ..:/mnt/sf
