services:
  lint:
    build:
      context: .
      dockerfile: golint.Dockerfile
    working_dir: /go/src/github.com/GruffGemini/simplefeatures
    entrypoint: golangci-lint run --max-same-issues 100
    volumes:
      - ..:/go/src/github.com/GruffGemini/simplefeatures
    environment:
      - GO111MODULE=on
