version: "2.1"
services:
  geostests:
    image: peterstace/simplefeatures-ci:geos-${GEOS_VERSION}-go-1.20.4
    working_dir: /mnt/sf
    entrypoint: go test -test.count=1 -test.run=. ./geos
    volumes:
      - ..:/mnt/sf
