name: CI
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CI
      run: |
        env
        echo $GITHUB_WORKSPACE
        echo Add other actions to build,
        echo test, and deploy your project.
